LOCAL_URL="http://127.0.0.1:2024"
PRODUCTION_URL="https://gestaltai-146ee200f93f5d6688814feed1edce29.us.langgraph.app"
ENV="local"
NAME="MyChat"


LANGSMITH_TRACING="true"
LANGSMITH_ENDPOINT="https://api.smith.langchain.com"
LANGSMITH_API_KEY="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"
LANGSMITH_PROJECT="GestaltAI"
